fix error for new version deltachat-core (since 1.71.0)
In deltachat-core was removed option 'mvbox_watch',
after that `deltabot serve` issue error:
...
  File ".../python3.10/site-packages/deltachat/account.py", line 177, in set_config
    self._check_config_key(name)
  File ".../python3.10/site-packages/deltachat/account.py", line 136, in _check_config_key
    raise KeyError(f"{name!r} not a valid config key, existing keys: {self._configkeys!r}")
KeyError: "'mvbox_watch' not a valid config key, existing keys: ['addr', 'mail_server'...]